<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HEU-PEDRO-PRADIITA" name="Test" tests="1" failures="0" timestamp="25 Dec 2021 04:50:48 GMT" time="0.028" errors="0">
  <testcase name="@BeforeMethod BefMet" time="0.0" classname="script.LoginTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at resources.Base.initializeDriver(Base.java:35)
	at script.LoginTest.BefMet(LoginTest.java:33)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod BefMet -->
  <testcase name="@AfterMethod AfMet" time="0.0" classname="script.LoginTest">
    <skipped/>
  </testcase> <!-- @AfterMethod AfMet -->
  <testcase name="successLogin" time="0.007" classname="script.LoginTest">
    <skipped/>
  </testcase> <!-- successLogin -->
</testsuite> <!-- Test -->
